-- Wedding function decks: Sangeet and Mehndi colours and outfit styles (destination "wedding"). Colour cards use swatch
-- images drawn for this app (web/public/cards/wedding). Outfit-style cards link to image searches instead of hosting photos:
-- outfit photos on Wikimedia Commons are scarce and mostly traditional, and other sources are not ours to copy.
insert into swipe_decks (key, label, description, sort_order, destination) values ($q$wedding-sangeet-colours$q$, $q$Sangeet: colours$q$, $q$Colour palettes and how bride and groom combine them. Theme: Glitz & Glamour, indo-western.$q$, 10, 'wedding');
insert into swipe_decks (key, label, description, sort_order, destination) values ($q$wedding-sangeet-outfits$q$, $q$Sangeet: outfit styles$q$, $q$Bride and groom outfit styles for the Sangeet (14 Feb, second half).$q$, 20, 'wedding');
insert into swipe_decks (key, label, description, sort_order, destination) values ($q$wedding-mehndi-colours$q$, $q$Mehndi: colours$q$, $q$How to handle green at the mehndi, and colours that avoid the clash (14 Feb, first half).$q$, 30, 'wedding');
insert into swipe_decks (key, label, description, sort_order, destination) values ($q$wedding-mehndi-outfits$q$, $q$Mehndi: outfit styles$q$, $q$Comfortable bride and groom outfit styles for the Mehndi.$q$, 40, 'wedding');
insert into swipe_cards (deck_id, title, subtitle, detail, emoji, category, image_url, image_credit, facts, links, sort_order)
select d.id, v.title, v.subtitle, v.detail, v.emoji, v.category, v.image_url,
  case when v.image_url is null then null else 'Colour swatch drawn for this planner' end,
  v.facts::jsonb,
  jsonb_build_array(
    jsonb_build_object('label', 'See photos', 'url', 'https://www.google.com/search?tbm=isch&q=' || replace(v.search, ' ', '+')),
    jsonb_build_object('label', 'Pinterest', 'url', 'https://www.pinterest.com/search/pins/?q=' || replace(v.search, ' ', '+'))),
  v.sort_order
from swipe_decks d, (values
($q$Midnight navy and gold$q$, $q$Sangeet colour palette$q$, $q$Deep navy with gold embroidery and sequins. Looks rich under stage lights and photographs very well.$q$, $q$🎨$q$, $q$Colour$q$, $q$cards/wedding/sangeet-midnight-gold.svg$q$, $q$navy gold sequin lehenga sangeet$q$, $q$[{"label": "Colours", "value": "#0B1F4B, #C9A24B, #F3E3B0"}, {"label": "Theme fit", "value": "Glitz & Glamour, indo-western"}]$q$, 1),
($q$Champagne and rose gold$q$, $q$Sangeet colour palette$q$, $q$Soft metallic neutrals that glow in evening light. Easy for both of you and for family to match.$q$, $q$🎨$q$, $q$Colour$q$, $q$cards/wedding/sangeet-champagne-rosegold.svg$q$, $q$champagne rose gold sangeet outfit$q$, $q$[{"label": "Colours", "value": "#F2E0C8, #D9A08C, #B76E79"}, {"label": "Theme fit", "value": "Glitz & Glamour, indo-western"}]$q$, 2),
($q$Black and silver sequins$q$, $q$Sangeet colour palette$q$, $q$The most "glam" option: black with silver sequin or crystal work. Strong for the groom, bold for the bride.$q$, $q$🎨$q$, $q$Colour$q$, $q$cards/wedding/sangeet-black-silver.svg$q$, $q$black silver sequin saree gown sangeet$q$, $q$[{"label": "Colours", "value": "#0E0E10, #9AA0A6, #E8EAED"}, {"label": "Theme fit", "value": "Glitz & Glamour, indo-western"}]$q$, 3),
($q$Wine and antique gold$q$, $q$Sangeet colour palette$q$, $q$Deep red-wine tones with antique gold. Warm and festive, still very flattering on camera.$q$, $q$🎨$q$, $q$Colour$q$, $q$cards/wedding/sangeet-wine-gold.svg$q$, $q$wine maroon gold lehenga sangeet$q$, $q$[{"label": "Colours", "value": "#5B1326, #A5283E, #C9A24B"}, {"label": "Theme fit", "value": "Glitz & Glamour, indo-western"}]$q$, 4),
($q$Ice blue and silver$q$, $q$Sangeet colour palette$q$, $q$Cool, frosty and modern. A clear contrast to the warm haldi and mehndi days.$q$, $q$🎨$q$, $q$Colour$q$, $q$cards/wedding/sangeet-ice-silver.svg$q$, $q$ice blue silver lehenga sangeet$q$, $q$[{"label": "Colours", "value": "#CFE6F5, #9FB8CC, #E8EAED"}, {"label": "Theme fit", "value": "Glitz & Glamour, indo-western"}]$q$, 5),
($q$Blush pink and pearl$q$, $q$Sangeet colour palette$q$, $q$Romantic and soft, with pearl and crystal detail. Less "party", more fairytale.$q$, $q$🎨$q$, $q$Colour$q$, $q$cards/wedding/sangeet-blush-pearl.svg$q$, $q$blush pink pearl lehenga sangeet$q$, $q$[{"label": "Colours", "value": "#F6D5DA, #E7A9B5, #FAF3EC"}, {"label": "Theme fit", "value": "Glitz & Glamour, indo-western"}]$q$, 6),
($q$Royal purple and gold$q$, $q$Sangeet colour palette$q$, $q$A regal jewel tone that reads as glamorous without being the usual red or pink.$q$, $q$🎨$q$, $q$Colour$q$, $q$cards/wedding/sangeet-purple-gold.svg$q$, $q$royal purple gold gown lehenga sangeet$q$, $q$[{"label": "Colours", "value": "#4B1D6B, #7B3FA0, #C9A24B"}, {"label": "Theme fit", "value": "Glitz & Glamour, indo-western"}]$q$, 7),
($q$Emerald and gold$q$, $q$Sangeet colour palette$q$, $q$Rich green with gold. Lovely for the Sangeet, but note the mehndi green-clash question: keep this off the mehndi day.$q$, $q$🎨$q$, $q$Colour$q$, $q$cards/wedding/sangeet-emerald-gold.svg$q$, $q$emerald green gold lehenga sangeet$q$, $q$[{"label": "Colours", "value": "#0E5E4B, #1C8C6E, #C9A24B"}, {"label": "Theme fit", "value": "Glitz & Glamour, indo-western"}]$q$, 8),
($q$Fuchsia and silver$q$, $q$Sangeet colour palette$q$, $q$High energy and very "dance floor". Bright colour with silver instead of gold feels more modern.$q$, $q$🎨$q$, $q$Colour$q$, $q$cards/wedding/sangeet-fuchsia-silver.svg$q$, $q$fuchsia pink silver sangeet outfit$q$, $q$[{"label": "Colours", "value": "#C2185B, #E85D9A, #C0C0C8"}, {"label": "Theme fit", "value": "Glitz & Glamour, indo-western"}]$q$, 9),
($q$Copper and bronze$q$, $q$Sangeet colour palette$q$, $q$Warm metallics that suit most skin tones and photograph beautifully at night.$q$, $q$🎨$q$, $q$Colour$q$, $q$cards/wedding/sangeet-copper-bronze.svg$q$, $q$copper bronze metallic lehenga sangeet$q$, $q$[{"label": "Colours", "value": "#8C4A2F, #C57B4D, #E8B98A"}, {"label": "Theme fit", "value": "Glitz & Glamour, indo-western"}]$q$, 10),
($q$Ivory and crystal$q$, $q$Sangeet colour palette$q$, $q$All-white glam with crystals. Elegant, but needs care with stains and dance floors.$q$, $q$🎨$q$, $q$Colour$q$, $q$cards/wedding/sangeet-ivory-crystal.svg$q$, $q$ivory white crystal sangeet outfit$q$, $q$[{"label": "Colours", "value": "#FBF7EF, #E5E1D8, #BFD7EA"}, {"label": "Theme fit", "value": "Glitz & Glamour, indo-western"}]$q$, 11),
($q$Teal and rose gold$q$, $q$Sangeet colour palette$q$, $q$Teal with rose gold: unusual, fresh and still dressy.$q$, $q$🎨$q$, $q$Colour$q$, $q$cards/wedding/sangeet-teal-rosegold.svg$q$, $q$teal rose gold lehenga sangeet$q$, $q$[{"label": "Colours", "value": "#0E6B73, #2B9CA6, #D9A08C"}, {"label": "Theme fit", "value": "Glitz & Glamour, indo-western"}]$q$, 12),
($q$Matching palette$q$, $q$Both in the same palette$q$, $q$Bride and groom wear the same palette, for example both in navy and gold. Cleanest photos, and families can easily coordinate around it.$q$, $q$💞$q$, $q$Combination$q$, $q$cards/wedding/sangeet-combo-matching.svg$q$, $q$bride groom coordinated sangeet outfits$q$, $q$[{"label": "Top half of the picture", "value": "Bride"}, {"label": "Bottom half", "value": "Groom"}]$q$, 13),
($q$Bold bride, dark groom$q$, $q$Bride in colour, groom in black or navy$q$, $q$The bride wears the bright statement colour while the groom stays in black or deep navy with a small matching accent. Makes the bride stand out in photos.$q$, $q$💞$q$, $q$Combination$q$, $q$cards/wedding/sangeet-combo-contrast.svg$q$, $q$bride groom coordinated sangeet outfits$q$, $q$[{"label": "Top half of the picture", "value": "Bride"}, {"label": "Bottom half", "value": "Groom"}]$q$, 14),
($q$Groom echoes the accent$q$, $q$Groom picks up one detail from the bride$q$, $q$The groom stays neutral and picks up one detail from the bride's outfit: a pocket square, buttons or the lining of the jacket.$q$, $q$💞$q$, $q$Combination$q$, $q$cards/wedding/sangeet-combo-accent.svg$q$, $q$bride groom coordinated sangeet outfits$q$, $q$[{"label": "Top half of the picture", "value": "Bride"}, {"label": "Bottom half", "value": "Groom"}]$q$, 15)
) as v(title, subtitle, detail, emoji, category, image_url, search, facts, sort_order)
where d.key = 'wedding-sangeet-colours';
insert into swipe_cards (deck_id, title, subtitle, detail, emoji, category, image_url, image_credit, facts, links, sort_order)
select d.id, v.title, v.subtitle, v.detail, v.emoji, v.category, v.image_url,
  case when v.image_url is null then null else 'Colour swatch drawn for this planner' end,
  v.facts::jsonb,
  jsonb_build_array(
    jsonb_build_object('label', 'See photos', 'url', 'https://www.google.com/search?tbm=isch&q=' || replace(v.search, ' ', '+')),
    jsonb_build_object('label', 'Pinterest', 'url', 'https://www.pinterest.com/search/pins/?q=' || replace(v.search, ' ', '+'))),
  v.sort_order
from swipe_decks d, (values
($q$Lehenga with a cape or jacket$q$, $q$Bride outfit style$q$, $q$A sequin or embroidered lehenga with a cape or long jacket. Easy to dance in once the cape comes off, and very photogenic.$q$, $q$👗$q$, $q$Bride$q$, null, $q$bride sangeet lehenga cape$q$, $q$[{"label": "For", "value": "Bride"}, {"label": "Dance-friendly", "value": "Check before choosing"}]$q$, 1),
($q$Pre-draped saree gown$q$, $q$Bride outfit style$q$, $q$A sequin or crystal saree gown, pre-stitched drape. Glam, light, and far easier to dance in than a heavy lehenga.$q$, $q$👗$q$, $q$Bride$q$, null, $q$sequin pre draped saree gown sangeet$q$, $q$[{"label": "For", "value": "Bride"}, {"label": "Dance-friendly", "value": "Check before choosing"}]$q$, 2),
($q$Ruffle saree with embellished blouse$q$, $q$Bride outfit style$q$, $q$A ruffle or tulle saree with a heavily embellished blouse. Indo-western and playful.$q$, $q$👗$q$, $q$Bride$q$, null, $q$ruffle saree embellished blouse sangeet$q$, $q$[{"label": "For", "value": "Bride"}, {"label": "Dance-friendly", "value": "Check before choosing"}]$q$, 3),
($q$Crop top and skirt (indo-western)$q$, $q$Bride outfit style$q$, $q$Embellished crop top with a flared or trail skirt. Lightest of the lehenga styles.$q$, $q$👗$q$, $q$Bride$q$, null, $q$indo western crop top skirt sangeet bride$q$, $q$[{"label": "For", "value": "Bride"}, {"label": "Dance-friendly", "value": "Check before choosing"}]$q$, 4),
($q$Co-ord or jumpsuit$q$, $q$Bride outfit style$q$, $q$A sequin co-ord, palazzo set or jumpsuit. The most modern look and the most comfortable for the group dance.$q$, $q$👗$q$, $q$Bride$q$, null, $q$sequin jumpsuit palazzo co-ord sangeet bride$q$, $q$[{"label": "For", "value": "Bride"}, {"label": "Dance-friendly", "value": "Check before choosing"}]$q$, 5),
($q$Bandhgala suit$q$, $q$Groom outfit style$q$, $q$A tailored bandhgala (closed-neck jacket) in velvet or textured fabric, with subtle embroidery or buttons.$q$, $q$🤵$q$, $q$Groom$q$, null, $q$groom bandhgala sangeet velvet$q$, $q$[{"label": "For", "value": "Groom"}, {"label": "Dance-friendly", "value": "Check before choosing"}]$q$, 6),
($q$Velvet blazer over kurta$q$, $q$Groom outfit style$q$, $q$A velvet or brocade blazer over a plain kurta or shirt. Dressy and easy to move in.$q$, $q$🤵$q$, $q$Groom$q$, null, $q$groom velvet blazer kurta sangeet$q$, $q$[{"label": "For", "value": "Groom"}, {"label": "Dance-friendly", "value": "Check before choosing"}]$q$, 7),
($q$Sequin or embroidered jacket$q$, $q$Groom outfit style$q$, $q$A statement sequin or embroidered jacket over a simple kurta. This is the "bling" option for the groom.$q$, $q$🤵$q$, $q$Groom$q$, null, $q$groom sequin jacket kurta sangeet$q$, $q$[{"label": "For", "value": "Groom"}, {"label": "Dance-friendly", "value": "Check before choosing"}]$q$, 8),
($q$Indo-western sherwani$q$, $q$Groom outfit style$q$, $q$A short or sleeveless indo-western sherwani with a cape or drape. More formal than a jacket.$q$, $q$🤵$q$, $q$Groom$q$, null, $q$groom indo western sherwani sangeet$q$, $q$[{"label": "For", "value": "Groom"}, {"label": "Dance-friendly", "value": "Check before choosing"}]$q$, 9),
($q$Tuxedo with a Nehru collar$q$, $q$Groom outfit style$q$, $q$A tuxedo-style jacket with a Nehru collar and no tie. Sharp and modern.$q$, $q$🤵$q$, $q$Groom$q$, null, $q$groom tuxedo nehru collar sangeet$q$, $q$[{"label": "For", "value": "Groom"}, {"label": "Dance-friendly", "value": "Check before choosing"}]$q$, 10)
) as v(title, subtitle, detail, emoji, category, image_url, search, facts, sort_order)
where d.key = 'wedding-sangeet-outfits';
insert into swipe_cards (deck_id, title, subtitle, detail, emoji, category, image_url, image_credit, facts, links, sort_order)
select d.id, v.title, v.subtitle, v.detail, v.emoji, v.category, v.image_url,
  case when v.image_url is null then null else 'Colour swatch drawn for this planner' end,
  v.facts::jsonb,
  jsonb_build_array(
    jsonb_build_object('label', 'See photos', 'url', 'https://www.google.com/search?tbm=isch&q=' || replace(v.search, ' ', '+')),
    jsonb_build_object('label', 'Pinterest', 'url', 'https://www.pinterest.com/search/pins/?q=' || replace(v.search, ' ', '+'))),
  v.sort_order
from swipe_decks d, (values
($q$Bride in green, guests asked to avoid green$q$, $q$Bride stands out$q$, $q$The bride wears green and family and friends are asked, nicely and early, to wear other colours. Gives the cleanest photos, but needs a message in the family groups and some people will ignore it.$q$, $q$🚫$q$, $q$Decision$q$, $q$cards/wedding/mehndi-plan-1.svg$q$, $q$mehndi function outfits colours$q$, $q$[{"label": "Question", "value": "How do we handle green at the mehndi?"}]$q$, 1),
($q$Bride in green, guests wear anything$q$, $q$Relaxed$q$, $q$Nothing is requested. The bride may be one of many people in green, so make her outfit clearly different (rich fabric, heavy dupatta, a bolder shade) so she still stands out.$q$, $q$🌿$q$, $q$Decision$q$, $q$cards/wedding/mehndi-plan-2.svg$q$, $q$mehndi function outfits colours$q$, $q$[{"label": "Question", "value": "How do we handle green at the mehndi?"}]$q$, 2),
($q$Bride in a non-green colour$q$, $q$Avoids the clash$q$, $q$The bride wears another colour (yellow, coral, pink or lavender) so green guests are not a problem.$q$, $q$🎨$q$, $q$Decision$q$, $q$cards/wedding/mehndi-plan-3.svg$q$, $q$mehndi function outfits colours$q$, $q$[{"label": "Question", "value": "How do we handle green at the mehndi?"}]$q$, 3),
($q$Everyone in green: a green mehndi$q$, $q$Embrace it$q$, $q$Make green the theme. Bride and everyone dress in green shades, with decor in marigold and cream so it feels intentional.$q$, $q$🌱$q$, $q$Decision$q$, $q$cards/wedding/mehndi-plan-4.svg$q$, $q$mehndi function outfits colours$q$, $q$[{"label": "Question", "value": "How do we handle green at the mehndi?"}]$q$, 4),
($q$Yellow and mustard$q$, $q$Mehndi colour (no green)$q$, $q$A classic mehndi colour that is bright and does not clash with green. Close to the haldi theme though, so it may blur the two days.$q$, $q$🎨$q$, $q$Colour$q$, $q$cards/wedding/mehndi-yellow-mustard.svg$q$, $q$yellow mustard mehndi outfit$q$, $q$[{"label": "Colours", "value": "#E8B400, #C48A00, #FFF1B8"}, {"label": "Green clash", "value": "None"}]$q$, 5),
($q$Coral and peach$q$, $q$Mehndi colour (no green)$q$, $q$Warm and soft, and it looks great beside green decor.$q$, $q$🎨$q$, $q$Colour$q$, $q$cards/wedding/mehndi-coral-peach.svg$q$, $q$coral peach mehndi outfit lehenga$q$, $q$[{"label": "Colours", "value": "#F28C6B, #F8B79B, #FFE3D3"}, {"label": "Green clash", "value": "None"}]$q$, 6),
($q$Magenta and hot pink$q$, $q$Mehndi colour (no green)$q$, $q$Bold and festive. Pairs naturally with green and marigold decor.$q$, $q$🎨$q$, $q$Colour$q$, $q$cards/wedding/mehndi-magenta-pink.svg$q$, $q$magenta pink mehndi outfit$q$, $q$[{"label": "Colours", "value": "#C2185B, #E85D9A, #F8BBD0"}, {"label": "Green clash", "value": "None"}]$q$, 7),
($q$Lavender and lilac$q$, $q$Mehndi colour (no green)$q$, $q$Pastel and modern. Good if you want a softer look than the usual bright mehndi colours.$q$, $q$🎨$q$, $q$Colour$q$, $q$cards/wedding/mehndi-lavender-lilac.svg$q$, $q$lavender lilac mehndi outfit$q$, $q$[{"label": "Colours", "value": "#B9A3E3, #D9CCF2, #F3EEFB"}, {"label": "Green clash", "value": "None"}]$q$, 8),
($q$White with a pastel pop$q$, $q$Mehndi colour (no green)$q$, $q$Lucknowi chikankari or white with a pastel dupatta. Light and elegant, and stays cool in February sun.$q$, $q$🎨$q$, $q$Colour$q$, $q$cards/wedding/mehndi-white-pastel.svg$q$, $q$white chikankari pastel mehndi outfit$q$, $q$[{"label": "Colours", "value": "#FBF7EF, #F8BBD0, #BFD7EA"}, {"label": "Green clash", "value": "None"}]$q$, 9),
($q$Orange and saffron$q$, $q$Mehndi colour (no green)$q$, $q$Warm, festive and cheerful. Works with green decor and marigold flowers.$q$, $q$🎨$q$, $q$Colour$q$, $q$cards/wedding/mehndi-orange-saffron.svg$q$, $q$orange saffron mehndi outfit$q$, $q$[{"label": "Colours", "value": "#F57C00, #FFB300, #FFE0B2"}, {"label": "Green clash", "value": "None"}]$q$, 10),
($q$Powder blue and silver$q$, $q$Mehndi colour (no green)$q$, $q$Cool and calm against a warm, green setting. Looks different from what most guests will wear.$q$, $q$🎨$q$, $q$Colour$q$, $q$cards/wedding/mehndi-powder-blue.svg$q$, $q$powder blue silver mehndi outfit$q$, $q$[{"label": "Colours", "value": "#B9D7EA, #8FB4D0, #E8EAED"}, {"label": "Green clash", "value": "None"}]$q$, 11),
($q$Dusty rose and gold$q$, $q$Mehndi colour (no green)$q$, $q$Muted, elegant and easy to match across ages.$q$, $q$🎨$q$, $q$Colour$q$, $q$cards/wedding/mehndi-dusty-rose.svg$q$, $q$dusty rose gold mehndi outfit$q$, $q$[{"label": "Colours", "value": "#D79A9F, #E8C0C3, #C9A24B"}, {"label": "Green clash", "value": "None"}]$q$, 12),
($q$Rani pink with yellow$q$, $q$Mehndi colour (no green)$q$, $q$The classic bright mehndi pairing: very photogenic and very festive.$q$, $q$🎨$q$, $q$Colour$q$, $q$cards/wedding/mehndi-rani-yellow.svg$q$, $q$rani pink yellow mehndi outfit$q$, $q$[{"label": "Colours", "value": "#C2185B, #E8B400, #FFF1B8"}, {"label": "Green clash", "value": "None"}]$q$, 13)
) as v(title, subtitle, detail, emoji, category, image_url, search, facts, sort_order)
where d.key = 'wedding-mehndi-colours';
insert into swipe_cards (deck_id, title, subtitle, detail, emoji, category, image_url, image_credit, facts, links, sort_order)
select d.id, v.title, v.subtitle, v.detail, v.emoji, v.category, v.image_url,
  case when v.image_url is null then null else 'Colour swatch drawn for this planner' end,
  v.facts::jsonb,
  jsonb_build_array(
    jsonb_build_object('label', 'See photos', 'url', 'https://www.google.com/search?tbm=isch&q=' || replace(v.search, ' ', '+')),
    jsonb_build_object('label', 'Pinterest', 'url', 'https://www.pinterest.com/search/pins/?q=' || replace(v.search, ' ', '+'))),
  v.sort_order
from swipe_decks d, (values
($q$Sharara set$q$, $q$Bride outfit style$q$, $q$A light sharara set with a short kurta and dupatta. Comfortable for sitting while the mehndi is applied.$q$, $q$👗$q$, $q$Bride$q$, null, $q$bride sharara set mehndi$q$, $q$[{"label": "For", "value": "Bride"}, {"label": "Comfort", "value": "Day event, mostly sitting"}]$q$, 1),
($q$Light lehenga$q$, $q$Bride outfit style$q$, $q$A lighter fabric lehenga in a soft colour (georgette, organza). Dressy without being heavy.$q$, $q$👗$q$, $q$Bride$q$, null, $q$bride light lehenga mehndi function$q$, $q$[{"label": "For", "value": "Bride"}, {"label": "Comfort", "value": "Day event, mostly sitting"}]$q$, 2),
($q$Anarkali$q$, $q$Bride outfit style$q$, $q$A flowing anarkali with a dupatta. Easy to sit in and to move around.$q$, $q$👗$q$, $q$Bride$q$, null, $q$bride anarkali mehndi function$q$, $q$[{"label": "For", "value": "Bride"}, {"label": "Comfort", "value": "Day event, mostly sitting"}]$q$, 3),
($q$Co-ord with a long jacket$q$, $q$Bride outfit style$q$, $q$A modern co-ord set or a kurta with a long jacket. Easiest while your hands are being decorated.$q$, $q$👗$q$, $q$Bride$q$, null, $q$bride co-ord set jacket mehndi$q$, $q$[{"label": "For", "value": "Bride"}, {"label": "Comfort", "value": "Day event, mostly sitting"}]$q$, 4),
($q$Saree$q$, $q$Bride outfit style$q$, $q$A light, pre-draped or easy saree. Elegant, but check you can sit and eat comfortably.$q$, $q$👗$q$, $q$Bride$q$, null, $q$bride saree mehndi function$q$, $q$[{"label": "For", "value": "Bride"}, {"label": "Comfort", "value": "Day event, mostly sitting"}]$q$, 5),
($q$Kurta pyjama$q$, $q$Groom outfit style$q$, $q$A simple pastel or white kurta pyjama. Fits the relaxed mood of the mehndi.$q$, $q$🤵$q$, $q$Groom$q$, null, $q$groom kurta pyjama mehndi$q$, $q$[{"label": "For", "value": "Groom"}, {"label": "Comfort", "value": "Day event, mostly sitting"}]$q$, 6),
($q$Kurta with Nehru jacket$q$, $q$Groom outfit style$q$, $q$A kurta with a printed or textured Nehru jacket. A little dressier, in a colour that matches the bride.$q$, $q$🤵$q$, $q$Groom$q$, null, $q$groom kurta nehru jacket mehndi$q$, $q$[{"label": "For", "value": "Groom"}, {"label": "Comfort", "value": "Day event, mostly sitting"}]$q$, 7),
($q$Short kurta with a printed jacket$q$, $q$Groom outfit style$q$, $q$A short kurta over trousers with a printed jacket. Modern and casual.$q$, $q$🤵$q$, $q$Groom$q$, null, $q$groom short kurta printed jacket mehndi$q$, $q$[{"label": "For", "value": "Groom"}, {"label": "Comfort", "value": "Day event, mostly sitting"}]$q$, 8)
) as v(title, subtitle, detail, emoji, category, image_url, search, facts, sort_order)
where d.key = 'wedding-mehndi-outfits';
