-- Wedding function decks, part 2: Haldi and the wedding day (baraat, varmala, mandap shaadi). Same shape as 0022.
-- Colour cards use swatch images drawn for this app; outfit cards link to image searches.
insert into swipe_decks (key, label, description, sort_order, destination) values ($q$wedding-haldi-colours$q$, $q$Haldi: colours$q$, $q$Yellow and genda phool palettes and couple combinations (15 Feb, first half).$q$, 50, 'wedding');
insert into swipe_decks (key, label, description, sort_order, destination) values ($q$wedding-haldi-outfits$q$, $q$Haldi: outfit styles$q$, $q$Light, washable outfit styles for the messy haldi.$q$, 60, 'wedding');
insert into swipe_decks (key, label, description, sort_order, destination) values ($q$wedding-shaadi-colours$q$, $q$Wedding day: colours$q$, $q$Bride colours and couple combinations for the baraat, varmala and pheras (15 Feb, second half).$q$, 70, 'wedding');
insert into swipe_decks (key, label, description, sort_order, destination) values ($q$wedding-shaadi-outfits$q$, $q$Wedding day: outfit styles$q$, $q$Bride and groom outfits and accessories for a long night.$q$, 80, 'wedding');
insert into swipe_cards (deck_id, title, subtitle, detail, emoji, category, image_url, image_credit, facts, links, sort_order)
select d.id, v.title, v.subtitle, v.detail, v.emoji, v.category, v.image_url,
  case when v.image_url is null then null else 'Colour swatch drawn for this planner' end,
  v.facts::jsonb,
  jsonb_build_array(
    jsonb_build_object('label', 'See photos', 'url', 'https://www.google.com/search?tbm=isch&q=' || replace(v.search, ' ', '+')),
    jsonb_build_object('label', 'Pinterest', 'url', 'https://www.pinterest.com/search/pins/?q=' || replace(v.search, ' ', '+'))),
  v.sort_order
from swipe_decks d, (values
($q$Marigold and white$q$, $q$Haldi colour palette$q$, $q$Genda-phool yellow with white. The classic haldi look: bright in photos and easy for guests to match. Haldi is messy, so pick outfits you do not mind staining.$q$, $q$🌼$q$, $q$Colour$q$, $q$cards/wedding/haldi-marigold-white.svg$q$, $q$marigold yellow white haldi outfit$q$, $q$[{"label": "Colours", "value": "#F2A900, #F7C948, #FBF7EF"}, {"label": "Theme fit", "value": "Yellow and genda phool shades"}]$q$, 1),
($q$Mustard and ivory$q$, $q$Haldi colour palette$q$, $q$A deeper, earthier yellow with ivory. Looks rich rather than loud. Haldi is messy, so pick outfits you do not mind staining.$q$, $q$🌼$q$, $q$Colour$q$, $q$cards/wedding/haldi-mustard-ivory.svg$q$, $q$mustard ivory haldi outfit$q$, $q$[{"label": "Colours", "value": "#C48A00, #E3B341, #F6EBD0"}, {"label": "Theme fit", "value": "Yellow and genda phool shades"}]$q$, 2),
($q$Lemon and pastel$q$, $q$Haldi colour palette$q$, $q$Light lemon with a pastel pink. Soft and pretty, but marks show more. Haldi is messy, so pick outfits you do not mind staining.$q$, $q$🌼$q$, $q$Colour$q$, $q$cards/wedding/haldi-lemon-pastel.svg$q$, $q$lemon yellow pastel haldi outfit$q$, $q$[{"label": "Colours", "value": "#F5E663, #FBF2A6, #F8D9E0"}, {"label": "Theme fit", "value": "Yellow and genda phool shades"}]$q$, 3),
($q$Yellow and orange$q$, $q$Haldi colour palette$q$, $q$Marigold in two tones, yellow and orange, like the flowers. Very warm and cheerful. Haldi is messy, so pick outfits you do not mind staining.$q$, $q$🌼$q$, $q$Colour$q$, $q$cards/wedding/haldi-yellow-orange.svg$q$, $q$yellow orange marigold haldi outfit$q$, $q$[{"label": "Colours", "value": "#F2A900, #F57C00, #FFE0B2"}, {"label": "Theme fit", "value": "Yellow and genda phool shades"}]$q$, 4),
($q$Yellow and pink$q$, $q$Haldi colour palette$q$, $q$Yellow with a pop of pink. Playful and good for friends and cousins. Haldi is messy, so pick outfits you do not mind staining.$q$, $q$🌼$q$, $q$Colour$q$, $q$cards/wedding/haldi-yellow-pink.svg$q$, $q$yellow pink haldi outfit$q$, $q$[{"label": "Colours", "value": "#F7C948, #E85D9A, #FFF1B8"}, {"label": "Theme fit", "value": "Yellow and genda phool shades"}]$q$, 5),
($q$Yellow and sage$q$, $q$Haldi colour palette$q$, $q$Yellow with soft sage green, like leaves and flowers together. Calm and a little different. Haldi is messy, so pick outfits you do not mind staining.$q$, $q$🌼$q$, $q$Colour$q$, $q$cards/wedding/haldi-yellow-sage.svg$q$, $q$yellow sage green haldi outfit$q$, $q$[{"label": "Colours", "value": "#F2C94C, #A9BFA0, #F6F1DC"}, {"label": "Theme fit", "value": "Yellow and genda phool shades"}]$q$, 6),
($q$White with floral pops$q$, $q$Haldi colour palette$q$, $q$White cotton with yellow and pink flowers, or fresh-flower jewellery. Light, but white gets stained. Haldi is messy, so pick outfits you do not mind staining.$q$, $q$🌼$q$, $q$Colour$q$, $q$cards/wedding/haldi-white-floral.svg$q$, $q$white cotton floral jewellery haldi$q$, $q$[{"label": "Colours", "value": "#FBF7EF, #F2A900, #E85D9A"}, {"label": "Theme fit", "value": "Yellow and genda phool shades"}]$q$, 7),
($q$Sunflower and cream$q$, $q$Haldi colour palette$q$, $q$Bright sunflower yellow with cream. Cheerful and very photogenic in daylight. Haldi is messy, so pick outfits you do not mind staining.$q$, $q$🌼$q$, $q$Colour$q$, $q$cards/wedding/haldi-sunflower-cream.svg$q$, $q$sunflower yellow cream haldi outfit$q$, $q$[{"label": "Colours", "value": "#E8B400, #F6D86B, #FFF8DC"}, {"label": "Theme fit", "value": "Yellow and genda phool shades"}]$q$, 8),
($q$Matching yellows$q$, $q$Bride and groom in the same yellow$q$, $q$Both in the same shade of yellow. Clean photos, and the family can match one clear colour.$q$, $q$💞$q$, $q$Combination$q$, $q$cards/wedding/haldi-combo-matching.svg$q$, $q$bride groom haldi outfit coordinated$q$, $q$[{"label": "Top half of the picture", "value": "Bride"}, {"label": "Bottom half", "value": "Groom"}]$q$, 9),
($q$Yellow bride, white groom$q$, $q$Bride in yellow, groom in white or cream$q$, $q$The bride wears yellow and the groom wears white or cream with a yellow stole or dupatta. Easy to keep clean-looking.$q$, $q$💞$q$, $q$Combination$q$, $q$cards/wedding/haldi-combo-white-groom.svg$q$, $q$bride groom haldi outfit coordinated$q$, $q$[{"label": "Top half of the picture", "value": "Bride"}, {"label": "Bottom half", "value": "Groom"}]$q$, 10),
($q$Pastel pair$q$, $q$Soft yellow with a pastel kurta$q$, $q$Bride in soft lemon or pastel yellow, groom in a pastel kurta (peach, mint or powder blue). Fresh and modern.$q$, $q$💞$q$, $q$Combination$q$, $q$cards/wedding/haldi-combo-pastel-pair.svg$q$, $q$bride groom haldi outfit coordinated$q$, $q$[{"label": "Top half of the picture", "value": "Bride"}, {"label": "Bottom half", "value": "Groom"}]$q$, 11)
) as v(title, subtitle, detail, emoji, category, image_url, search, facts, sort_order)
where d.key = 'wedding-haldi-colours';
insert into swipe_cards (deck_id, title, subtitle, detail, emoji, category, image_url, image_credit, facts, links, sort_order)
select d.id, v.title, v.subtitle, v.detail, v.emoji, v.category, v.image_url,
  case when v.image_url is null then null else 'Colour swatch drawn for this planner' end,
  v.facts::jsonb,
  jsonb_build_array(
    jsonb_build_object('label', 'See photos', 'url', 'https://www.google.com/search?tbm=isch&q=' || replace(v.search, ' ', '+')),
    jsonb_build_object('label', 'Pinterest', 'url', 'https://www.pinterest.com/search/pins/?q=' || replace(v.search, ' ', '+'))),
  v.sort_order
from swipe_decks d, (values
($q$Cotton or chanderi lehenga$q$, $q$Bride outfit style$q$, $q$A light cotton, chanderi or organza lehenga in yellow. Breathable, and easier to wash or replace than silk.$q$, $q$👗$q$, $q$Bride$q$, null, $q$bride cotton chanderi yellow lehenga haldi$q$, $q$[{"label": "For", "value": "Bride"}, {"label": "Messy event", "value": "Pick something you can stain"}]$q$, 1),
($q$Sharara or palazzo set$q$, $q$Bride outfit style$q$, $q$A yellow sharara or palazzo set with a short kurta. Easy to sit on the floor and to move around in.$q$, $q$👗$q$, $q$Bride$q$, null, $q$bride yellow sharara palazzo haldi$q$, $q$[{"label": "For", "value": "Bride"}, {"label": "Messy event", "value": "Pick something you can stain"}]$q$, 2),
($q$Anarkali or kurta set$q$, $q$Bride outfit style$q$, $q$A simple anarkali or kurta set with a light dupatta. The most comfortable and the cheapest to risk staining.$q$, $q$👗$q$, $q$Bride$q$, null, $q$bride yellow anarkali kurta haldi$q$, $q$[{"label": "For", "value": "Bride"}, {"label": "Messy event", "value": "Pick something you can stain"}]$q$, 3),
($q$Light saree$q$, $q$Bride outfit style$q$, $q$A yellow cotton or georgette saree. Elegant, but check you can sit and be messy in it.$q$, $q$👗$q$, $q$Bride$q$, null, $q$bride yellow saree haldi$q$, $q$[{"label": "For", "value": "Bride"}, {"label": "Messy event", "value": "Pick something you can stain"}]$q$, 4),
($q$Fresh-flower jewellery$q$, $q$Bride outfit style$q$, $q$Marigold and rose flower jewellery (necklace, earrings, maang tikka, bracelets) instead of gold. Very photogenic and a haldi tradition.$q$, $q$🌼$q$, $q$Bride$q$, null, $q$bride flower jewellery haldi marigold$q$, $q$[{"label": "For", "value": "Bride"}, {"label": "Messy event", "value": "Pick something you can stain"}]$q$, 5),
($q$Yellow kurta$q$, $q$Groom outfit style$q$, $q$A plain yellow kurta pyjama. The simplest, and matches the bride.$q$, $q$🤵$q$, $q$Groom$q$, null, $q$groom yellow kurta haldi$q$, $q$[{"label": "For", "value": "Groom"}, {"label": "Messy event", "value": "Pick something you can stain"}]$q$, 6),
($q$White kurta with a yellow stole$q$, $q$Groom outfit style$q$, $q$A white or cream kurta with a yellow dupatta or stole. A clean look, but white shows stains.$q$, $q$🤵$q$, $q$Groom$q$, null, $q$groom white kurta yellow stole haldi$q$, $q$[{"label": "For", "value": "Groom"}, {"label": "Messy event", "value": "Pick something you can stain"}]$q$, 7),
($q$Pastel kurta and jacket$q$, $q$Groom outfit style$q$, $q$A pastel kurta with a printed or plain jacket. Dressier, and not yellow-on-yellow.$q$, $q$🤵$q$, $q$Groom$q$, null, $q$groom pastel kurta jacket haldi$q$, $q$[{"label": "For", "value": "Groom"}, {"label": "Messy event", "value": "Pick something you can stain"}]$q$, 8)
) as v(title, subtitle, detail, emoji, category, image_url, search, facts, sort_order)
where d.key = 'wedding-haldi-outfits';
insert into swipe_cards (deck_id, title, subtitle, detail, emoji, category, image_url, image_credit, facts, links, sort_order)
select d.id, v.title, v.subtitle, v.detail, v.emoji, v.category, v.image_url,
  case when v.image_url is null then null else 'Colour swatch drawn for this planner' end,
  v.facts::jsonb,
  jsonb_build_array(
    jsonb_build_object('label', 'See photos', 'url', 'https://www.google.com/search?tbm=isch&q=' || replace(v.search, ' ', '+')),
    jsonb_build_object('label', 'Pinterest', 'url', 'https://www.pinterest.com/search/pins/?q=' || replace(v.search, ' ', '+'))),
  v.sort_order
from swipe_decks d, (values
($q$Bride: classic red and gold$q$, $q$Wedding day colour$q$, $q$Traditional bridal red with gold zari. Timeless and the safest choice for the pheras.$q$, $q$🎨$q$, $q$Colour$q$, $q$cards/wedding/shaadi-red-gold.svg$q$, $q$bridal red gold lehenga wedding$q$, $q$[{"label": "Colours", "value": "#B3121F, #D4A017, #F3E3B0"}, {"label": "Guests", "value": "No dress code (decided)"}]$q$, 1),
($q$Bride: maroon and gold$q$, $q$Wedding day colour$q$, $q$Deep maroon with gold. Rich and a little more modern than bright red.$q$, $q$🎨$q$, $q$Colour$q$, $q$cards/wedding/shaadi-maroon-gold.svg$q$, $q$bridal maroon gold lehenga$q$, $q$[{"label": "Colours", "value": "#5B1326, #8C2338, #C9A24B"}, {"label": "Guests", "value": "No dress code (decided)"}]$q$, 2),
($q$Bride: rani pink and gold$q$, $q$Wedding day colour$q$, $q$Rani or hot pink with gold. Bright and festive.$q$, $q$🎨$q$, $q$Colour$q$, $q$cards/wedding/shaadi-pink-gold.svg$q$, $q$bridal rani pink gold lehenga$q$, $q$[{"label": "Colours", "value": "#C2185B, #E85D9A, #D4A017"}, {"label": "Guests", "value": "No dress code (decided)"}]$q$, 3),
($q$Bride: blush and gold$q$, $q$Wedding day colour$q$, $q$Soft blush with gold work. Light and romantic.$q$, $q$🎨$q$, $q$Colour$q$, $q$cards/wedding/shaadi-blush-gold.svg$q$, $q$bridal blush pink gold lehenga$q$, $q$[{"label": "Colours", "value": "#F2C9C4, #E7A9B5, #C9A24B"}, {"label": "Guests", "value": "No dress code (decided)"}]$q$, 4),
($q$Bride: ivory and gold$q$, $q$Wedding day colour$q$, $q$Ivory or cream with gold. Elegant and very modern, but stains show.$q$, $q$🎨$q$, $q$Colour$q$, $q$cards/wedding/shaadi-ivory-gold.svg$q$, $q$bridal ivory gold lehenga$q$, $q$[{"label": "Colours", "value": "#FBF4E4, #F0E0B8, #C9A24B"}, {"label": "Guests", "value": "No dress code (decided)"}]$q$, 5),
($q$Bride: powder blue and silver$q$, $q$Wedding day colour$q$, $q$A cool pastel instead of red. Unusual, and it stands out among red-dressed relatives.$q$, $q$🎨$q$, $q$Colour$q$, $q$cards/wedding/shaadi-pastel-blue.svg$q$, $q$bridal powder blue lehenga$q$, $q$[{"label": "Colours", "value": "#B9D7EA, #8FB4D0, #C0C0C8"}, {"label": "Guests", "value": "No dress code (decided)"}]$q$, 6),
($q$Bride: bottle green and gold$q$, $q$Wedding day colour$q$, $q$Deep green with gold. Rich and different.$q$, $q$🎨$q$, $q$Colour$q$, $q$cards/wedding/shaadi-green-gold.svg$q$, $q$bridal bottle green gold lehenga$q$, $q$[{"label": "Colours", "value": "#14532D, #1F7A4D, #C9A24B"}, {"label": "Guests", "value": "No dress code (decided)"}]$q$, 7),
($q$Red bride, ivory-gold groom$q$, $q$Bride in red, groom in ivory or cream with gold$q$, $q$The classic pairing: a red lehenga with an ivory or cream sherwani in gold. Always works in photos.$q$, $q$💞$q$, $q$Combination$q$, $q$cards/wedding/shaadi-combo-gold-pair.svg$q$, $q$bride groom wedding outfit colour combination$q$, $q$[{"label": "Top half of the picture", "value": "Bride"}, {"label": "Bottom half", "value": "Groom"}]$q$, 8),
($q$Matching tones$q$, $q$Groom echoes the bride$q$, $q$The groom's sherwani picks up the bride's colour in a lighter shade (blush with blush, maroon with maroon).$q$, $q$💞$q$, $q$Combination$q$, $q$cards/wedding/shaadi-combo-tone-match.svg$q$, $q$bride groom wedding outfit colour combination$q$, $q$[{"label": "Top half of the picture", "value": "Bride"}, {"label": "Bottom half", "value": "Groom"}]$q$, 9),
($q$Pastel pair$q$, $q$Both in soft pastels$q$, $q$Both in soft pastels (blush, powder blue or sage) with gold or silver. Modern, but stands apart from the family's reds.$q$, $q$💞$q$, $q$Combination$q$, $q$cards/wedding/shaadi-combo-pastel-pair.svg$q$, $q$bride groom wedding outfit colour combination$q$, $q$[{"label": "Top half of the picture", "value": "Bride"}, {"label": "Bottom half", "value": "Groom"}]$q$, 10)
) as v(title, subtitle, detail, emoji, category, image_url, search, facts, sort_order)
where d.key = 'wedding-shaadi-colours';
insert into swipe_cards (deck_id, title, subtitle, detail, emoji, category, image_url, image_credit, facts, links, sort_order)
select d.id, v.title, v.subtitle, v.detail, v.emoji, v.category, v.image_url,
  case when v.image_url is null then null else 'Colour swatch drawn for this planner' end,
  v.facts::jsonb,
  jsonb_build_array(
    jsonb_build_object('label', 'See photos', 'url', 'https://www.google.com/search?tbm=isch&q=' || replace(v.search, ' ', '+')),
    jsonb_build_object('label', 'Pinterest', 'url', 'https://www.pinterest.com/search/pins/?q=' || replace(v.search, ' ', '+'))),
  v.sort_order
from swipe_decks d, (values
($q$Heavy bridal lehenga$q$, $q$Bride outfit style$q$, $q$A traditional heavy lehenga with embroidery and dupatta. It can be heavy, and the night runs to midnight, so plan breaks.$q$, $q$👗$q$, $q$Bride$q$, null, $q$heavy bridal lehenga wedding$q$, $q$[{"label": "For", "value": "Bride"}, {"label": "Long night", "value": "Baraat, varmala and pheras run to midnight"}]$q$, 1),
($q$Lehenga with a lighter skirt$q$, $q$Bride outfit style$q$, $q$A bridal lehenga with a lighter, flared skirt and heavy blouse and dupatta. Same look at a lower weight.$q$, $q$👗$q$, $q$Bride$q$, null, $q$light weight bridal lehenga$q$, $q$[{"label": "For", "value": "Bride"}, {"label": "Long night", "value": "Baraat, varmala and pheras run to midnight"}]$q$, 2),
($q$Banarasi saree$q$, $q$Bride outfit style$q$, $q$A Banarasi or silk bridal saree with gold zari. Classic, and lighter to wear through a long night.$q$, $q$👗$q$, $q$Bride$q$, null, $q$banarasi bridal saree wedding$q$, $q$[{"label": "For", "value": "Bride"}, {"label": "Long night", "value": "Baraat, varmala and pheras run to midnight"}]$q$, 3),
($q$Lehenga with a veil or cape$q$, $q$Bride outfit style$q$, $q$A lehenga with a long veil or a cape for the varmala and entry. Dramatic in photos.$q$, $q$👗$q$, $q$Bride$q$, null, $q$bridal lehenga with cape veil$q$, $q$[{"label": "For", "value": "Bride"}, {"label": "Long night", "value": "Baraat, varmala and pheras run to midnight"}]$q$, 4),
($q$Sherwani$q$, $q$Groom outfit style$q$, $q$A traditional sherwani in ivory, cream or a deep colour, with embroidery. The default for the baraat and pheras.$q$, $q$🤵$q$, $q$Groom$q$, null, $q$groom sherwani wedding ivory$q$, $q$[{"label": "For", "value": "Groom"}, {"label": "Long night", "value": "Baraat, varmala and pheras run to midnight"}]$q$, 5),
($q$Achkan$q$, $q$Groom outfit style$q$, $q$A long achkan with a high collar. Formal and a bit lighter-looking than a heavy sherwani.$q$, $q$🤵$q$, $q$Groom$q$, null, $q$groom achkan wedding$q$, $q$[{"label": "For", "value": "Groom"}, {"label": "Long night", "value": "Baraat, varmala and pheras run to midnight"}]$q$, 6),
($q$Bandhgala$q$, $q$Groom outfit style$q$, $q$A tailored bandhgala suit in a rich colour. Sharp and easy to wear through the night.$q$, $q$🤵$q$, $q$Groom$q$, null, $q$groom bandhgala wedding$q$, $q$[{"label": "For", "value": "Groom"}, {"label": "Long night", "value": "Baraat, varmala and pheras run to midnight"}]$q$, 7),
($q$Safa, kalgi and stole$q$, $q$Groom outfit style$q$, $q$The accessories: a turban (safa) with a kalgi brooch, a stole and mojaris. Decide these alongside the outfit.$q$, $q$🤵$q$, $q$Groom$q$, null, $q$groom safa kalgi stole sherwani$q$, $q$[{"label": "For", "value": "Groom"}, {"label": "Long night", "value": "Baraat, varmala and pheras run to midnight"}]$q$, 8)
) as v(title, subtitle, detail, emoji, category, image_url, search, facts, sort_order)
where d.key = 'wedding-shaadi-outfits';
