-- Wedding day decor deck (mandap, colours, flowers, lighting, bride entry, varmala), plus one Haldi couple combination
-- from Paridhi's 22 Sep message (bright pink bride, light pink groom). Photos are Wikimedia Commons, credited on each card.
insert into swipe_decks (key, label, description, sort_order, destination) values ($q$wedding-shaadi-decor$q$, $q$Wedding day: mandap, entry and varmala$q$, $q$Mandap style, colours, flowers, lighting, bride entry and the varmala (15 Feb, second half).$q$, 90, 'wedding');
insert into swipe_cards (deck_id, title, subtitle, detail, emoji, category, image_url, image_credit, image_source_url, facts, links, sort_order)
select d.id, v.title, v.subtitle, v.detail, v.emoji, v.category, v.image_url, v.image_credit, v.image_source_url,
  v.facts::jsonb,
  jsonb_build_array(
    jsonb_build_object('label', 'See photos', 'url', 'https://www.google.com/search?tbm=isch&q=' || replace(v.search, ' ', '+')),
    jsonb_build_object('label', 'Pinterest', 'url', 'https://www.pinterest.com/search/pins/?q=' || replace(v.search, ' ', '+'))),
  v.sort_order
from swipe_decks d, (values
($q$Classic dome mandap with draped pillars$q$, $q$Mandap style$q$, $q$A traditional pillared mandap with a dome, wrapped in fabric and topped with a white-and-pink flower garland. Familiar, photogenic and easy for a decorator to deliver.$q$, $q$🛕$q$, $q$Mandap$q$, $q$cards/wedding/decor-mandap-dome.jpg$q$, $q$Photo: Wikilover90, CC BY-SA 4.0, via Wikimedia Commons (cropped)$q$, $q$https://commons.wikimedia.org/wiki/File:Indian_Wedding_Mandap_Decoration.jpg$q$, $q$classic dome mandap wedding pillars flowers$q$, $q$[{"label": "Style", "value": "Traditional"}, {"label": "Venue", "value": "Hotel Sai, Bawal (new property: check what it allows)"}]$q$, 1),
($q$Dense floral columns and garland canopy$q$, $q$Mandap style$q$, $q$Tall columns of red roses and white flowers with a garland canopy and a gold-draped backdrop. Very rich and full, with a lot of flowers and a higher cost.$q$, $q$🌹$q$, $q$Mandap$q$, $q$cards/wedding/decor-floral-columns.jpg$q$, $q$Photo: Kasyap, CC BY-SA 4.0, via Wikimedia Commons (cropped)$q$, $q$https://commons.wikimedia.org/wiki/File:Wedding_Stage.jpg$q$, $q$floral columns mandap stage roses jasmine garland canopy$q$, $q$[{"label": "Style", "value": "Rich, flower-heavy"}, {"label": "Venue", "value": "Hotel Sai, Bawal (new property: check what it allows)"}]$q$, 2),
($q$Minimal white and gold mandap$q$, $q$Mandap style$q$, $q$A clean white-and-gold frame with sheer drapes and a little greenery. Modern and calm, and it lets the bride and groom stand out.$q$, $q$🤍$q$, $q$Mandap$q$, null, null, null, $q$minimal white gold mandap modern indian wedding$q$, $q$[{"label": "Style", "value": "Modern, minimal"}, {"label": "Venue", "value": "Hotel Sai, Bawal (new property: check what it allows)"}]$q$, 3),
($q$Draped fabric canopy$q$, $q$Mandap style$q$, $q$A soft canopy of sheer fabric over four poles, with hanging flowers and lights. Light, romantic and works indoors or outdoors.$q$, $q$🪽$q$, $q$Mandap$q$, null, null, null, $q$draped fabric canopy mandap sheer wedding$q$, $q$[{"label": "Style", "value": "Soft, romantic"}, {"label": "Venue", "value": "Hotel Sai, Bawal (new property: check what it allows)"}]$q$, 4),
($q$Open mandap under a floral ceiling$q$, $q$Mandap style$q$, $q$No walls: a ceiling of hanging flowers or a "flower cloud" over the mandap. Dramatic from below, so check the ceiling height and the cost.$q$, $q$☁️$q$, $q$Mandap$q$, null, null, null, $q$floral ceiling mandap hanging flowers wedding$q$, $q$[{"label": "Style", "value": "Dramatic"}, {"label": "Venue", "value": "Hotel Sai, Bawal (new property: check what it allows)"}]$q$, 5),
($q$Heritage mandap with arches$q$, $q$Mandap style$q$, $q$Carved arches (jharokha style), brass lamps and rich fabric in maroon and gold. Looks royal and suits a traditional ceremony.$q$, $q$🏛️$q$, $q$Mandap$q$, null, null, null, $q$heritage jharokha mandap maroon gold wedding$q$, $q$[{"label": "Style", "value": "Royal, traditional"}, {"label": "Venue", "value": "Hotel Sai, Bawal (new property: check what it allows)"}]$q$, 6),
($q$Ivory, gold and greenery$q$, $q$Decor colour theme$q$, $q$Mostly white flowers and gold with plenty of green leaves. Fresh and elegant, and it goes with almost any bride colour. Pick this together with the bride's outfit colour.$q$, $q$🎨$q$, $q$Colour$q$, $q$cards/wedding/decor-ivory-gold-green.svg$q$, $q$Colour swatch drawn for this planner$q$, null, $q$ivory gold green mandap decor wedding$q$, $q$[{"label": "Colours", "value": "#FBF4E4, #C9A24B, #5E8C61"}]$q$, 7),
($q$Red, maroon and marigold$q$, $q$Decor colour theme$q$, $q$Deep red and maroon with marigold. Warm, traditional and very festive. Pick this together with the bride's outfit colour.$q$, $q$🎨$q$, $q$Colour$q$, $q$cards/wedding/decor-red-marigold.svg$q$, $q$Colour swatch drawn for this planner$q$, null, $q$red maroon marigold mandap decor$q$, $q$[{"label": "Colours", "value": "#8C1C26, #E8890C, #F2C94C"}]$q$, 8),
($q$Blush, ivory and gold$q$, $q$Decor colour theme$q$, $q$Soft pink and ivory flowers with gold. Romantic and light. Pick this together with the bride's outfit colour.$q$, $q$🎨$q$, $q$Colour$q$, $q$cards/wedding/decor-blush-gold.svg$q$, $q$Colour swatch drawn for this planner$q$, null, $q$blush pink ivory gold mandap decor$q$, $q$[{"label": "Colours", "value": "#F2C9C4, #FBF4E4, #C9A24B"}]$q$, 9),
($q$Pastel mix$q$, $q$Decor colour theme$q$, $q$Pink, powder blue and sage flowers together. Modern and soft, a little less traditional. Pick this together with the bride's outfit colour.$q$, $q$🎨$q$, $q$Colour$q$, $q$cards/wedding/decor-pastel-mix.svg$q$, $q$Colour swatch drawn for this planner$q$, null, $q$pastel flowers mandap decor wedding$q$, $q$[{"label": "Colours", "value": "#F8BBD0, #BFD7EA, #E3EBDD"}]$q$, 10),
($q$Jewel tones$q$, $q$Decor colour theme$q$, $q$Wine, emerald and gold. Rich and different. Pick this together with the bride's outfit colour.$q$, $q$🎨$q$, $q$Colour$q$, $q$cards/wedding/decor-jewel-tones.svg$q$, $q$Colour swatch drawn for this planner$q$, null, $q$jewel tone mandap decor wine emerald gold$q$, $q$[{"label": "Colours", "value": "#7B1E3A, #14532D, #C9A24B"}]$q$, 11),
($q$Marigold and rose$q$, $q$Flowers$q$, $q$Marigold (genda) with roses: the classic Indian wedding mix. Bright, affordable and easy to find in February.$q$, $q$🌼$q$, $q$Flowers$q$, $q$cards/wedding/decor-marigold-closeup.jpg$q$, $q$Photo: SnapMeUp, CC BY 4.0, via Wikimedia Commons$q$, $q$https://commons.wikimedia.org/wiki/File:Marigold_Flowers_as_garland_in_India.jpg$q$, $q$marigold rose mandap decor wedding$q$, $q$[{"label": "Look", "value": "Bright, traditional"}]$q$, 12),
($q$All-marigold garlands and strings$q$, $q$Flowers$q$, $q$Strings and curtains of marigold in yellow and orange for the backdrop and entrance. Low cost and very striking. Close to the haldi theme.$q$, $q$🌼$q$, $q$Flowers$q$, $q$cards/wedding/decor-marigold-garlands.jpg$q$, $q$Photo: পাপৰি বৰা, CC BY-SA 4.0, via Wikimedia Commons (cropped)$q$, $q$https://commons.wikimedia.org/wiki/File:Marigold_garlands.jpg$q$, $q$marigold curtain backdrop wedding entrance decor$q$, $q$[{"label": "Look", "value": "Bold, festive"}]$q$, 13),
($q$Jasmine (mogra) and tuberose$q$, $q$Flowers$q$, $q$White, fragrant flowers. The whole venue smells wonderful, but they wilt faster and cost more per string.$q$, $q$🤍$q$, $q$Flowers$q$, null, null, null, $q$mogra tuberose jasmine mandap decor wedding$q$, $q$[{"label": "Look", "value": "Fragrant, elegant"}]$q$, 14),
($q$White orchids, lilies and hydrangea$q$, $q$Flowers$q$, $q$Imported-style white flowers for a modern, upscale look. Costs more and depends on the season and the supplier.$q$, $q$🌸$q$, $q$Flowers$q$, null, null, null, $q$white orchid lily hydrangea mandap wedding decor$q$, $q$[{"label": "Look", "value": "Modern, upscale"}]$q$, 15),
($q$Fresh flowers or artificial$q$, $q$Decision$q$, $q$Fresh looks and smells best but wilts and costs more. Good artificial flowers last through a long night and cost less. A mix is common: fresh up close, artificial overhead.$q$, $q$⚖️$q$, $q$Flowers$q$, null, null, null, $q$fresh vs artificial flowers wedding mandap$q$, $q$[{"label": "Question", "value": "Fresh, artificial or a mix?"}]$q$, 16),
($q$Fairy-light backdrop with a floral ring$q$, $q$Lighting$q$, $q$A white drape wall with hanging fairy lights, a round floral frame and soft spotlights. Works well for the varmala stage and for photos at night.$q$, $q$✨$q$, $q$Lighting$q$, $q$cards/wedding/decor-fairy-lights.jpg$q$, $q$Photo: Vis M, CC BY-SA 4.0, via Wikimedia Commons$q$, $q$https://commons.wikimedia.org/wiki/File:Wedding_reception_stage,_decorations,_Kochi.jpg$q$, $q$fairy light backdrop floral ring wedding stage$q$, $q$[{"label": "Good for", "value": "Night photos"}]$q$, 17),
($q$Chandeliers, lanterns and candles$q$, $q$Lighting$q$, $q$Hanging chandeliers or lanterns with candles on the side tables. Warm and elegant. Check whether the venue allows open flames; battery candles are safer.$q$, $q$🕯️$q$, $q$Lighting$q$, null, null, null, $q$chandelier lantern candle wedding mandap decor$q$, $q$[{"label": "Check", "value": "Open flames and the venue"}]$q$, 18),
($q$Warm string-light canopy$q$, $q$Lighting$q$, $q$Strings of warm lights across the ceiling or over the mandap. Cheap, cosy and good in photos.$q$, $q$💡$q$, $q$Lighting$q$, null, null, null, $q$string light canopy wedding mandap$q$, $q$[{"label": "Look", "value": "Cosy"}]$q$, 19),
($q$Bride entry under a phoolon ki chaadar$q$, $q$Bride entry$q$, $q$Sisters, cousins or friends hold a canopy of flowers over the bride as she walks in. A well-loved tradition and great photos. Needs 4 people and a short rehearsal.$q$, $q$🌺$q$, $q$Entry$q$, null, null, null, $q$bride entry phoolon ki chaadar$q$, $q$[{"label": "Needs", "value": "4 people and a rehearsal"}]$q$, 20),
($q$Walk in with sisters and a petal path$q$, $q$Bride entry$q$, $q$The bride walks in with her sisters or friends along a path of petals. Simple and sweet, and easy to organise.$q$, $q$🌸$q$, $q$Entry$q$, null, null, null, $q$bride entry with sisters petals path wedding$q$, $q$[{"label": "Needs", "value": "Petals and a clear path"}]$q$, 21),
($q$Palki or doli entry$q$, $q$Bride entry$q$, $q$A decorated palanquin carried by relatives. Very traditional and dramatic. Check the venue, the floor and the number of people needed.$q$, $q$🛻$q$, $q$Entry$q$, null, null, null, $q$bride palki entry wedding doli$q$, $q$[{"label": "Check", "value": "Venue space and carriers"}]$q$, 22),
($q$Sparklers or cold-fire entry$q$, $q$Bride entry$q$, $q$Cold-fire fountains at the entrance, with music. Looks great at night, but check the venue rules, the ceiling and the smoke alarms.$q$, $q$🎆$q$, $q$Entry$q$, null, null, null, $q$cold pyro sparkler bride entry wedding$q$, $q$[{"label": "Check", "value": "Venue rules, indoors or outdoors"}]$q$, 23),
($q$Classic varmala with a petal shower$q$, $q$Varmala$q$, $q$The exchange of garlands on stage while family and friends shower petals. Simple, traditional and easy to photograph.$q$, $q$💐$q$, $q$Varmala$q$, null, null, null, $q$varmala jaimala petal shower wedding$q$, $q$[{"label": "Style", "value": "Classic"}]$q$, 24),
($q$Playful varmala with lifting$q$, $q$Varmala$q$, $q$Friends and cousins lift the bride and groom during the exchange, the fun "who gives in" moment. Great photos and energy, but only if you are both comfortable with it.$q$, $q$🎉$q$, $q$Varmala$q$, null, null, null, $q$jaimala lifting fun wedding varmala$q$, $q$[{"label": "Decide", "value": "Are both of us comfortable?"}]$q$, 25),
($q$Calm varmala, no lifting$q$, $q$Varmala$q$, $q$A graceful exchange with soft music, no lifting. Calmer and more private, and easier for heavy outfits.$q$, $q$🕊️$q$, $q$Varmala$q$, null, null, null, $q$graceful varmala exchange wedding calm$q$, $q$[{"label": "Style", "value": "Calm"}]$q$, 26),
($q$Heavy marigold and rose garlands$q$, $q$Varmala garlands$q$, $q$Thick, full garlands of marigold and roses. Look generous, but they are heavy and can be awkward to lift over a turban or veil.$q$, $q$🌹$q$, $q$Varmala$q$, $q$cards/wedding/decor-marigold-garlands.jpg$q$, $q$Photo: পাপৰি বৰা, CC BY-SA 4.0, via Wikimedia Commons (cropped)$q$, $q$https://commons.wikimedia.org/wiki/File:Marigold_garlands.jpg$q$, $q$heavy marigold rose varmala garland$q$, $q$[{"label": "Weight", "value": "Heavy"}]$q$, 27),
($q$Light mogra or jasmine garlands$q$, $q$Varmala garlands$q$, $q$Fragrant white garlands that are light and easy to exchange. Elegant, and kinder to the safa and the hair.$q$, $q$🤍$q$, $q$Varmala$q$, null, null, null, $q$mogra jasmine varmala garland light$q$, $q$[{"label": "Weight", "value": "Light"}]$q$, 28),
($q$Garlands with pearls or crystals$q$, $q$Varmala garlands$q$, $q$Flowers mixed with pearls or crystals. A more modern look that photographs well, and part of it can be kept as a memento.$q$, $q$📿$q$, $q$Varmala$q$, null, null, null, $q$varmala garland pearls crystals flowers$q$, $q$[{"label": "Look", "value": "Modern"}]$q$, 29)
) as v(title, subtitle, detail, emoji, category, image_url, image_credit, image_source_url, search, facts, sort_order)
where d.key = 'wedding-shaadi-decor';
insert into swipe_cards (deck_id, title, subtitle, detail, emoji, category, image_url, image_credit, facts, links, sort_order)
select d.id, $q$Bright pink bride, light pink groom$q$, $q$Paridhi's idea from 22 Sep$q$,
  $q$From the decor chat on 22 Sep: Paridhi suggested the two of you be the colourful ones at the haldi, bright pink for her and light pink for you, and remembered you being on board. Check it still works with the yellow theme around you.$q$,
  $q$💞$q$, $q$Combination$q$, $q$cards/wedding/haldi-combo-pink-pair.svg$q$, $q$Colour swatch drawn for this planner$q$,
  $q$[{"label": "Top half of the picture", "value": "Bride"}, {"label": "Bottom half", "value": "Groom"}]$q$::jsonb,
  jsonb_build_array(jsonb_build_object('label', 'See photos', 'url', 'https://www.google.com/search?tbm=isch&q=bright+pink+bride+light+pink+groom+haldi')),
  12
from swipe_decks d where d.key = 'wedding-haldi-colours';
