-- Decks for the gifts, photography and dance groups (destination 'wedding'). Gifts has nothing between the two of you
-- (decided: no wedding gift between the couple). Outfit-style cards elsewhere link to image searches; these cards do too.
insert into swipe_decks (key, label, description, sort_order, destination) values ($q$wedding-gifts$q$, $q$Gifts: family and guests$q$, $q$Gift ideas for family, guests and helpers. You two agreed there is no gift between you, so this is only for other people.$q$, 100, 'wedding');
insert into swipe_decks (key, label, description, sort_order, destination) values ($q$wedding-photography$q$, $q$Photography and video$q$, $q$What kind of photos and film you want, and which shots matter. Budget context from the chat: about 1.5 lakh hoped for, and one quote of 2 to 2.1 lakh all-inclusive.$q$, 110, 'wedding');
insert into swipe_decks (key, label, description, sort_order, destination) values ($q$wedding-dance$q$, $q$Sangeet: dance and performances$q$, $q$The Sangeet dance plan. You decided to start with small pieces and build up, and to practise about 30 minutes in the evening.$q$, 120, 'wedding');
insert into swipe_cards (deck_id, title, subtitle, detail, emoji, category, facts, links, sort_order)
select d.id, v.title, v.subtitle, v.detail, v.emoji, v.category, v.facts::jsonb,
  jsonb_build_array(
    jsonb_build_object('label', 'See ideas', 'url', 'https://www.google.com/search?tbm=isch&q=' || replace(v.search, ' ', '+')),
    jsonb_build_object('label', 'Pinterest', 'url', 'https://www.pinterest.com/search/pins/?q=' || replace(v.search, ' ', '+'))),
  v.sort_order
from swipe_decks d, (values
($q$Sweets and dry-fruit box$q$, $q$Return gift$q$, $q$A box of mithai or mixed dry fruits in a nice package. Everyone uses it, nothing is wasted, and it is easy to hand out at the exit.$q$, $q$🍬$q$, $q$Return gift$q$, $q$wedding return gift sweets dry fruit box$q$, $q$[{"label": "Cost", "value": "Low to medium"}, {"label": "Waste", "value": "None"}]$q$, 1),
($q$Plant or sapling$q$, $q$Return gift$q$, $q$A small potted plant or tulsi sapling with a thank-you tag. Meaningful, and good for guests who dislike clutter. Needs carrying care for guests travelling far.$q$, $q$🌱$q$, $q$Return gift$q$, $q$wedding return gift plant sapling tulsi$q$, $q$[{"label": "Cost", "value": "Low"}, {"label": "Travel", "value": "Awkward for long journeys"}]$q$, 2),
($q$Silver coin or small silver item$q$, $q$Return gift$q$, $q$A silver coin, diya or small bowl. Feels special and keeps its value. Costs more per guest, so it suits a smaller list or close family only.$q$, $q$🪙$q$, $q$Return gift$q$, $q$wedding return gift silver coin diya$q$, $q$[{"label": "Cost", "value": "Medium to high"}]$q$, 3),
($q$Diya, candle or decor set$q$, $q$Return gift$q$, $q$A handmade diya, candle or small decor piece. Good-looking and light to carry. Pick something simple that fits most homes.$q$, $q$🪔$q$, $q$Return gift$q$, $q$wedding return gift diya candle set$q$, $q$[{"label": "Cost", "value": "Low to medium"}]$q$, 4),
($q$Personalised keepsake$q$, $q$Return gift$q$, $q$A small item with your names and the date: a coaster, notebook, keychain or magnet. Lovely as a memento, but some guests will not keep it.$q$, $q$💌$q$, $q$Return gift$q$, $q$personalised wedding return gift names date$q$, $q$[{"label": "Cost", "value": "Low to medium"}, {"label": "Lead time", "value": "Order early"}]$q$, 5),
($q$Tote bag with local snacks$q$, $q$Return gift$q$, $q$A cloth bag with a few snacks from Delhi or Kolkata. Useful, light, and it ties in with where you come from.$q$, $q$👜$q$, $q$Return gift$q$, $q$wedding return gift tote bag snacks hamper$q$, $q$[{"label": "Cost", "value": "Medium"}]$q$, 6),
($q$Donation in the guests' name$q$, $q$Return gift$q$, $q$Instead of a gift, a donation to a cause and a small card telling guests about it. Nothing to carry or waste, but some guests like to receive something in hand.$q$, $q$🤝$q$, $q$Return gift$q$, $q$wedding favour donation in guests name card$q$, $q$[{"label": "Cost", "value": "You choose"}, {"label": "Waste", "value": "None"}]$q$, 7),
($q$Room welcome hamper$q$, $q$Welcome gift$q$, $q$A small basket in out-of-town guests' rooms: water, snacks, a schedule card and a map. Helpful at a new property like Hotel Sai. Ask the hotel what they allow and what they charge.$q$, $q$🧺$q$, $q$Welcome gift$q$, $q$wedding welcome hamper hotel room guests$q$, $q$[{"label": "For", "value": "Out-of-town guests"}, {"label": "Check", "value": "Hotel rules and charges"}]$q$, 8),
($q$Printed schedule and map card$q$, $q$Welcome gift$q$, $q$A one-page card with the function times (14 and 15 Feb), venue directions and a contact number. Costs almost nothing and saves a lot of calls.$q$, $q$🗺️$q$, $q$Welcome gift$q$, $q$wedding welcome card schedule itinerary$q$, $q$[{"label": "Cost", "value": "Very low"}]$q$, 9),
($q$Saree or shawl for the mothers$q$, $q$Family gift$q$, $q$A good saree, shawl or stole for each mother. A traditional way to thank them, and a gift they will keep. Ask what they like before you buy.$q$, $q$🧣$q$, $q$Family gift$q$, $q$gift for mother of bride groom saree shawl wedding$q$, $q$[{"label": "For", "value": "Mothers"}]$q$, 10),
($q$Something for the fathers$q$, $q$Family gift$q$, $q$A kurta set, a stole, a watch or a framed photo. Keep it personal rather than expensive.$q$, $q$🎁$q$, $q$Family gift$q$, $q$gift for father of bride groom wedding$q$, $q$[{"label": "For", "value": "Fathers"}]$q$, 11),
($q$Framed family photo$q$, $q$Family gift$q$, $q$A good framed family photograph from the wedding, delivered after the album is ready. Personal and timeless, but it comes after the wedding.$q$, $q$🖼️$q$, $q$Family gift$q$, $q$framed family photo gift wedding parents$q$, $q$[{"label": "Timing", "value": "After the wedding"}]$q$, 12),
($q$Gifts for siblings and cousins$q$, $q$Family gift$q$, $q$A matching small gift for each sibling and cousin who helps: a watch, a perfume, or something from their wish list. Ask the family group for ideas (this is still open in the planner).$q$, $q$🎀$q$, $q$Family gift$q$, $q$gift for sibling cousin wedding helpers$q$, $q$[{"label": "Planner", "value": "Family gift ideas: asked, not yet answered"}]$q$, 13),
($q$Bridesmaid and groomsmen gifts$q$, $q$Friends$q$, $q$A small gift box for close friends who stand with you: a keepsake, a skincare or grooming set, or a personalised item.$q$, $q$🥂$q$, $q$Friends$q$, $q$bridesmaid groomsmen gift box ideas india$q$, $q$[{"label": "For", "value": "Close friends"}]$q$, 14),
($q$Thank-you gifts for the pandit and helpers$q$, $q$Thanks$q$, $q$Dakshina for the pandit, plus small envelopes or gifts for the people who helped run the function. Decide the amounts before the day and put them in separate labelled envelopes.$q$, $q$🙏$q$, $q$Thanks$q$, $q$wedding shagun envelopes pandit helpers staff$q$, $q$[{"label": "Prepare", "value": "Envelopes and amounts in advance"}]$q$, 15),
($q$Tips for hotel and vendor staff$q$, $q$Thanks$q$, $q$Envelopes for hotel staff, drivers and the decor and catering teams. Hand over through one trusted person so it is fair and nothing is forgotten.$q$, $q$💼$q$, $q$Thanks$q$, $q$wedding tipping vendors staff india envelopes$q$, $q$[{"label": "Prepare", "value": "One person to hand them out"}]$q$, 16),
($q$Handwritten thank-you notes$q$, $q$Thanks$q$, $q$A short note to your closest family and friends after the wedding. Takes time but means a lot, and costs nothing.$q$, $q$✍️$q$, $q$Thanks$q$, $q$wedding thank you note ideas family$q$, $q$[{"label": "Cost", "value": "Time"}]$q$, 17)
) as v(title, subtitle, detail, emoji, category, search, facts, sort_order)
where d.key = 'wedding-gifts';
insert into swipe_cards (deck_id, title, subtitle, detail, emoji, category, facts, links, sort_order)
select d.id, v.title, v.subtitle, v.detail, v.emoji, v.category, v.facts::jsonb,
  jsonb_build_array(
    jsonb_build_object('label', 'See ideas', 'url', 'https://www.google.com/search?tbm=isch&q=' || replace(v.search, ' ', '+')),
    jsonb_build_object('label', 'Pinterest', 'url', 'https://www.pinterest.com/search/pins/?q=' || replace(v.search, ' ', '+'))),
  v.sort_order
from swipe_decks d, (values
($q$Candid, natural photos$q$, $q$Photo style$q$, $q$Unposed moments: laughs, reactions, family emotions. The photographer stays in the background. The modern favourite, but you still need a few posed family groups.$q$, $q$📷$q$, $q$Style$q$, $q$candid wedding photography india natural moments$q$, $q$[{"label": "Feel", "value": "Natural"}]$q$, 1),
($q$Traditional posed portraits$q$, $q$Photo style$q$, $q$Planned group and couple portraits, the classic way. Safe for family albums and elders, but it can feel stiff and takes time.$q$, $q$🖼️$q$, $q$Style$q$, $q$traditional posed wedding portraits india family$q$, $q$[{"label": "Feel", "value": "Formal"}]$q$, 2),
($q$A mix of candid and posed$q$, $q$Photo style$q$, $q$Candid through the day, with a short list of posed family and couple shots at set times. Most couples choose this.$q$, $q$🎯$q$, $q$Style$q$, $q$wedding photography candid and traditional mix$q$, $q$[{"label": "Feel", "value": "Balanced"}]$q$, 3),
($q$Bright and airy colours$q$, $q$Look$q$, $q$Light, clean, soft colours. Fresh and modern, and it flatters pastel outfits and decor.$q$, $q$☀️$q$, $q$Look$q$, $q$bright airy wedding photography india$q$, $q$[{"label": "Mood", "value": "Light and fresh"}]$q$, 4),
($q$Warm and rich colours$q$, $q$Look$q$, $q$Deeper, golden tones with rich colour. Suits red, gold and marigold, and festive nights.$q$, $q$🌅$q$, $q$Look$q$, $q$warm rich colour wedding photography india gold$q$, $q$[{"label": "Mood", "value": "Warm and festive"}]$q$, 5),
($q$Moody and cinematic$q$, $q$Look$q$, $q$Darker, higher contrast, film-like. Dramatic and stylish, but it can look heavy on bright haldi and mehndi days.$q$, $q$🎞️$q$, $q$Look$q$, $q$cinematic moody wedding photography india$q$, $q$[{"label": "Mood", "value": "Dramatic"}]$q$, 6),
($q$Cinematic wedding film$q$, $q$Video$q$, $q$A 5 to 10 minute highlight film with music, edited like a short movie. The thing most couples rewatch.$q$, $q$🎬$q$, $q$Video$q$, $q$cinematic wedding highlight film india$q$, $q$[{"label": "Deliverable", "value": "5 to 10 minute film"}]$q$, 7),
($q$Full-length ceremony video$q$, $q$Video$q$, $q$The whole ceremony recorded in one go, including the pheras. Long, but it is the only record of the whole night.$q$, $q$📹$q$, $q$Video$q$, $q$full length wedding ceremony video india$q$, $q$[{"label": "Deliverable", "value": "Full ceremony"}]$q$, 8),
($q$Short teaser or reel$q$, $q$Video$q$, $q$A 30 to 60 second teaser or reel for sharing quickly, often within a week or two.$q$, $q$📱$q$, $q$Video$q$, $q$wedding teaser reel instagram india$q$, $q$[{"label": "Deliverable", "value": "30 to 60 seconds"}]$q$, 9),
($q$Drone shots$q$, $q$Add-on$q$, $q$Aerial shots of the venue and the baraat. Check the venue allows drones and whether it is safe with crowds.$q$, $q$🚁$q$, $q$Add-on$q$, $q$wedding drone shots india baraat$q$, $q$[{"label": "Check", "value": "Venue permission"}]$q$, 10),
($q$Same-day edit or quick preview$q$, $q$Add-on$q$, $q$A few edited photos sent the same night or next morning. Fun to share, and some teams charge extra.$q$, $q$⚡$q$, $q$Add-on$q$, $q$same day edit wedding photos preview$q$, $q$[{"label": "Extra cost", "value": "Often"}]$q$, 11),
($q$Pre-wedding shoot$q$, $q$Extra shoot$q$, $q$A separate couple shoot before the wedding for the save-the-date or the screens at the event. Plan time and a location. One of the shortlisted teams has a pre-wedding film section on their page.$q$, $q$💑$q$, $q$Extra shoot$q$, $q$pre wedding shoot ideas delhi couple$q$, $q$[{"label": "Decide", "value": "Do we want one?"}]$q$, 12),
($q$Album: flush-mount or coffee-table$q$, $q$Deliverable$q$, $q$A printed album of the best photos. Pick the size and number of pages in advance, because it affects the price.$q$, $q$📖$q$, $q$Deliverable$q$, $q$wedding album design flush mount india$q$, $q$[{"label": "Decide", "value": "Pages and size"}]$q$, 13),
($q$Digital gallery only$q$, $q$Deliverable$q$, $q$An online gallery you can share with family, with no printed album. Cheaper and quicker. Print favourites later.$q$, $q$☁️$q$, $q$Deliverable$q$, $q$wedding online photo gallery share family$q$, $q$[{"label": "Cost", "value": "Lower"}]$q$, 14),
($q$Photos of every function$q$, $q$Coverage$q$, $q$Cover Tilak, Mehndi, Sagai, Sangeet (14 Feb) and Haldi, Baraat, Varmala and the Mandap shaadi (15 Feb). The longest day is 15 Feb, running to midnight, so ask about the team size and breaks.$q$, $q$📅$q$, $q$Coverage$q$, $q$wedding photography coverage all functions india$q$, $q$[{"label": "Days", "value": "14 and 15 Feb 2027"}]$q$, 15),
($q$Two days: Sangeet and wedding only$q$, $q$Coverage$q$, $q$Cover only the Sangeet and the wedding day, and have a relative cover the smaller events. Lower cost, but you lose haldi and mehndi photos.$q$, $q$🎯$q$, $q$Coverage$q$, $q$wedding photography two functions only$q$, $q$[{"label": "Cost", "value": "Lower"}]$q$, 16),
($q$Must-have: getting-ready and details$q$, $q$Key shots$q$, $q$The outfits, jewellery, mehndi hands, shoes and invitation, and the mandap before guests arrive. Easy to forget and not possible to redo.$q$, $q$💍$q$, $q$Key shots$q$, $q$wedding detail shots jewellery mehndi hands invitation$q$, $q$[{"label": "When", "value": "Before each function"}]$q$, 17),
($q$Must-have: family portraits$q$, $q$Key shots$q$, $q$A list of family combinations (both families, siblings, grandparents) with one person to call each group. Takes 15 to 20 minutes and is the part elders care about.$q$, $q$👨‍👩‍👧‍👦$q$, $q$Key shots$q$, $q$wedding family portrait shot list india$q$, $q$[{"label": "Plan", "value": "A written shot list"}]$q$, 18),
($q$Must-have: couple portraits$q$, $q$Key shots$q$, $q$A short, unhurried slot for the two of you in good light, ideally before the baraat or during golden hour. Decide the time in advance.$q$, $q$❤️$q$, $q$Key shots$q$, $q$couple portraits wedding day golden hour india$q$, $q$[{"label": "Plan", "value": "A set time and place"}]$q$, 19),
($q$Must-have: the Sangeet performances$q$, $q$Key shots$q$, $q$Every group dance and the couple's dance, filmed from two angles. The cousins are working on routines already, so tell the team the order.$q$, $q$💃$q$, $q$Key shots$q$, $q$sangeet performance videography india$q$, $q$[{"label": "Plan", "value": "Share the performance order"}]$q$, 20),
($q$Photographer sample check$q$, $q$How to choose$q$, $q$Ask each team for a full gallery and a full video from one real wedding of a similar size, not only highlights. A friend in the field has offered to vet the work.$q$, $q$🔍$q$, $q$How to choose$q$, $q$how to choose wedding photographer india questions$q$, $q$[{"label": "Tip", "value": "See a whole wedding, not highlights"}]$q$, 21)
) as v(title, subtitle, detail, emoji, category, search, facts, sort_order)
where d.key = 'wedding-photography';
insert into swipe_cards (deck_id, title, subtitle, detail, emoji, category, facts, links, sort_order)
select d.id, v.title, v.subtitle, v.detail, v.emoji, v.category, v.facts::jsonb,
  jsonb_build_array(
    jsonb_build_object('label', 'See ideas', 'url', 'https://www.google.com/search?tbm=isch&q=' || replace(v.search, ' ', '+')),
    jsonb_build_object('label', 'Pinterest', 'url', 'https://www.pinterest.com/search/pins/?q=' || replace(v.search, ' ', '+'))),
  v.sort_order
from swipe_decks d, (values
($q$Couple dance: romantic and slow$q$, $q$Couple dance$q$, $q$A slow, romantic number, with simple steps and a few lifts or spins. Easiest to learn and the most emotional on the night.$q$, $q$💞$q$, $q$Couple dance$q$, $q$romantic couple dance sangeet choreography slow$q$, $q$[{"label": "Difficulty", "value": "Easy"}]$q$, 1),
($q$Couple dance: high-energy Bollywood$q$, $q$Couple dance$q$, $q$A fun, upbeat Bollywood song with clear steps that you can practise in pieces. Gets the room clapping.$q$, $q$🎶$q$, $q$Couple dance$q$, $q$bollywood couple dance sangeet high energy choreography$q$, $q$[{"label": "Difficulty", "value": "Medium"}]$q$, 2),
($q$Couple dance: a medley of 3 songs$q$, $q$Couple dance$q$, $q$Three short pieces joined together: slow, then fun, then a big finish. Fits your plan of small pieces built up, and keeps each part short.$q$, $q$🎼$q$, $q$Couple dance$q$, $q$couple dance medley sangeet three songs$q$, $q$[{"label": "Difficulty", "value": "Medium"}, {"label": "Fits plan", "value": "Small pieces, joined up"}]$q$, 3),
($q$Couple dance: retro and classic$q$, $q$Couple dance$q$, $q$Older Hindi film songs with a classic feel. Beloved by elders and easy on the steps, and it photographs beautifully.$q$, $q$📻$q$, $q$Couple dance$q$, $q$retro bollywood couple dance sangeet classic songs$q$, $q$[{"label": "Difficulty", "value": "Easy to medium"}]$q$, 4),
($q$Couple dance: indo-western mashup$q$, $q$Couple dance$q$, $q$A mashup of Hindi and English tracks that matches the Glitz & Glamour theme. Needs a good audio edit, which the DJ or a studio can do.$q$, $q$✨$q$, $q$Couple dance$q$, $q$indo western mashup couple dance sangeet$q$, $q$[{"label": "Difficulty", "value": "Medium to hard"}, {"label": "Needs", "value": "Audio mix"}]$q$, 5),
($q$Couple dance: a surprise to start, then a joke$q$, $q$Couple dance$q$, $q$Start serious and romantic, then break into something silly. Gets laughs, and takes pressure off the dance.$q$, $q$😄$q$, $q$Couple dance$q$, $q$funny twist couple dance sangeet$q$, $q$[{"label": "Difficulty", "value": "Medium"}]$q$, 6),
($q$Grand entry dance$q$, $q$Entry$q$, $q$The two of you enter the Sangeet with a short dance or a walk with a fast beat. Sets the mood for the night.$q$, $q$🚪$q$, $q$Entry$q$, $q$sangeet couple grand entry dance idea$q$, $q$[{"label": "Length", "value": "About 1 to 2 minutes"}]$q$, 7),
($q$Learn with a choreographer$q$, $q$Learning$q$, $q$A few sessions with a choreographer for the couple dance and the group pieces. Faster and more polished, but it costs money and sets dates.$q$, $q$🧑‍🏫$q$, $q$Learning$q$, $q$sangeet choreographer delhi couple dance classes$q$, $q$[{"label": "Cost", "value": "Paid"}]$q$, 8),
($q$Learn from videos at home$q$, $q$Learning$q$, $q$Follow online tutorials in 30-minute evening sessions. Free and flexible, which matches your plan. It can be hard to fix mistakes alone.$q$, $q$📲$q$, $q$Learning$q$, $q$sangeet couple dance tutorial video learn at home$q$, $q$[{"label": "Cost", "value": "Free"}, {"label": "Fits plan", "value": "30 minutes in the evening"}]$q$, 9),
($q$Cousins' group dance$q$, $q$Group dance$q$, $q$The cousins are already picking reels and routines. Choose one or two group pieces with the same easy hook step so more people can join, with one person as the lead who teaches the steps.$q$, $q$👯$q$, $q$Group dance$q$, $q$sangeet group dance cousins choreography easy steps$q$, $q$[{"label": "Planner", "value": "Cousins coordinating informally"}]$q$, 10),
($q$Bride-side and groom-side face-off$q$, $q$Group dance$q$, $q$Two short performances, one from each side, in a friendly competition. Fun and gets both families involved.$q$, $q$🥁$q$, $q$Group dance$q$, $q$sangeet bride side groom side dance face off$q$, $q$[{"label": "Energy", "value": "High"}]$q$, 11),
($q$Parents' dance$q$, $q$Group dance$q$, $q$A short, easy performance by the parents, or all four together. Often the highlight of the night. Ask them early so they are comfortable.$q$, $q$🧑‍🤝‍🧑$q$, $q$Group dance$q$, $q$parents dance sangeet performance idea$q$, $q$[{"label": "Ask", "value": "Early, and keep it easy"}]$q$, 12),
($q$Friends' flash-mob moment$q$, $q$Group dance$q$, $q$Friends join in from the audience in the middle of a song and break into a planned routine. Fun, and a good surprise.$q$, $q$🎉$q$, $q$Group dance$q$, $q$sangeet flash mob friends surprise dance$q$, $q$[{"label": "Needs", "value": "A secret rehearsal"}]$q$, 13),
($q$Open dance floor with a DJ$q$, $q$Group dance$q$, $q$No planned routines beyond the couple dance. The DJ plays and everyone dances. The least effort, and good for people who do not like rehearsing.$q$, $q$🎧$q$, $q$Open floor$q$, $q$sangeet dj open dance floor playlist india$q$, $q$[{"label": "Effort", "value": "Lowest"}]$q$, 14),
($q$Rehearsal on the day$q$, $q$Practical$q$, $q$A short stage run-through of all performances before the Sangeet, with the lights and sound. Avoids surprises with the stage and the music.$q$, $q$🎤$q$, $q$Practical$q$, $q$sangeet rehearsal stage sound check dance$q$, $q$[{"label": "When", "value": "Morning or afternoon of 14 Feb"}]$q$, 15)
) as v(title, subtitle, detail, emoji, category, search, facts, sort_order)
where d.key = 'wedding-dance';
